#
#  sample logstash config
#    inject file from logs/access.log
#    to http endpoint
#    to elasticsearch
#
version: '3'
services:
  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.3
    volumes:
      - ./logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      # logs dirs
      - ./logs/:/logs/:ro
    environment:
      #
      # send to http endpoint
      #
      LOGSTASH_URL: ${LOGSTASH_URL:-}
      LOGSTASH_USER: ${LOGSTASH_USER:-}
      LOGSTASH_PASSWORD: ${LOGSTASH_PASSWORD:-}
      #
      # send to elasticsearch
      #
      ELASTICSEARCH_HOST: ${ELASTICSEARCH_HOST:-}
      ELASTICSEARCH_USER: ${ELASTICSEARCH_USER:-}
      ELASTICSEARCH_PASSWORD: ${ELASTICSEARCH_PASSWORD:-}
    networks:
      - elk

networks:
  elk:
    driver: bridge


